            <h1>Vous trouvez notre site génial? dites-le nous</h1> 

            <form action="index.php?page=livredor" method="post">


                <h2 class="Title">Identification</h2>

                <div class="row">

                <div class="col-md-6">
                    <form action="../apps/livredor.php" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label for="champNom" class="col-sm-2 control-label">Nom : </label>
                            <div class="col-sm-10">
                                <input type="text" name="nom"  value="<?php echo $nom ?>" id="champNom" placeholder="Veuillez renseigner votre nom *" maxlength="37" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="champPrenom" class="col-sm-2 control-label">Prénom : </label>
                            <div class="col-sm-10">
                                <input type="text" name="prenom"  id="champPrenom" value="<?php echo $prenom ?>" placeholder="Veuillez renseigner votre prénom *" maxlength="37" class="form-control">
                            </div>
                         </div>
                        <div class="form-group">
                            <label for="champEmail" class="col-sm-2 control-label">Email : </label>
                            <div class="col-sm-10">
                                <input type="email" name="email"  value="<?php echo $email ?>" id="champEmail" maxlength="37" placeholder="Veuillez renseigner votre email *" class="form-control">
                            </div>
                         </div>

                        <div class="form-group">              
                            <label for="captcha" class="col-sm-2 control-label">Recopiez le mot : "<?php echo captcha(); ?>"</label>
                            <div class="col-sm-10">
                                <input type="text" name="captcha" id="captcha" value="<?php echo $captcha ?>" maxlength="37" class="form-control"/><br />
                            </div>
                        </div>
                    </form>    
                </div>

                <div class="col-md-6">
                    <form action="../apps/livredor.php" method="post" class="form-horizontal">
                        <h2 class="Title">Votre commentaire</h2>
                        <div class="form-group">              
                            <label for="champCom" class="col-sm-3 control-label">Commentaire : </label>
                                <div class="col-sm-9">
                                     <textarea name="commentaire" class="champCom" maxlength="300" placeholder="pas plus de 300 caractères" class="form-control" max-width="100%"><?php echo $commentaire ?></textarea>
                                </div>
                        </div>
                        <button type="submit">Envoyer</button>
                    </form>
                </div>


 







<!--
remarques :
- maxlenght à 37 pour tous les champs de saisie (sauf textaerea à 300). taille de renseignement maximum :
    on ne peux metre que 37 W. faudras être sur que cela marche pour tous les email
- les champs nom, prénom ainsi que le commentaire est obligatoire. j'ai mis un required pour nom et prénom
    pour le textarea, on gère cela dans le PHP






-->


