<div class="row">

	<div class="col-md-12"><?= $message ?>
		<header class="page-header">
			<h1>Articles list <small>Looking for an article ?</small></h1>
		</header>
	</div>

	<div class="col-md-12">
		<h2>Publish an article</h2>

		<form method="post" action="index.php?page=articles" enctype="multipart/form-data">

			<div class="form-group">
				<label>Category</label><br />
				<label class="radio-inline">
					<input type="radio" name="category" id="cat1" value="Announcement"> Announcement
				</label>
				<label class="radio-inline">
					<input type="radio" name="category" id="cat2" value="Spoiler"> Spoiler
				</label>
				<label class="radio-inline">
					<input type="radio" name="category" id="cat3" value="People"> People
				</label>
				<label class="radio-inline">
					<input type="radio" name="category" id="cat4" value="Event"> Event
				</label>
			</div>

			<div class="form-group">
				<label for="title">Title</label>
				<input type="text" class="form-control" id="title" name="title">
			</div>

			<div class="form-group">
				<label for="content">Content</label>
				<textarea class="form-control" id="content" name="content"></textarea>
			</div>
			<button type="submit" name="action" value="publish_article" class="btn btn-primary">Publish your article</button>
		</form>

		<p id="pagination"><?= 'Go to page:'.implode("", pagination($pagin, $nbPage, 3, '?page=articles&amp;pagin='));?></p>
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<th>Title</th>
					<th>Author</th>
					<th>Published</th>
					<th>Updated</th>
					<th>Category</th>
				</thead>
				<?php
				displayLoop($select2);
				?>
			</table>
		</div> 
	</div>
</div>