<div class="container">
	<div class="row">

		<div class="col-md-6 col-sd-12">
			<form method="" action="">
				<fieldset>

					<legend>Nouvelles informations :</legend>

					<div class="form-group">
                        <label for="newmail" class="col-md-5 control-label formconfig">Nouvel email : </label>
                        <div class="col-md-7">
                        	<input type="email" name="newmail"  id="newmail" value="" placeholder="Entrer une adresse email" maxlength="64" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newphone" class="col-md-5 control-label formconfig">Nouveau téléphone : </label>
                        <div class="col-md-7">
                        	<input type="text" name="newphone"  id="newphone" value="" placeholder="Entrer un numéro téléphonique" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>
                    
                    <button type="submit" name="validation" class="col-md-12 formconfig">Valider</button>
                    

				</fieldset>

				<fieldset>

					<legend>Nouvelle adresse :</legend>

                    <div class="form-group">
                        <label for="newstreet" class="col-md-5 control-label formconfig">Nouvelle rue : </label>
                        <div class="col-md-7">
                        	<input type="text" name="newstreet"  id="newstreet" value="" placeholder="Entrer une nouvelle rue" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newpostal" class="col-md-5 control-label formconfig">Nouveau code postal : </label>
                        <div class="col-md-7">
                        	<input type="text" name="newpostal"  id="newpostal" value="" placeholder="Entrer un nouveau code postal" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newcity" class="col-md-5 control-label formconfig">Nouvelle ville : </label>
                        <div class="col-md-7">
                        	<input type="text" name="newcity"  id="newcity" value="" placeholder="Entrer une nouvelle ville" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newcountry" class="col-md-5 control-label formconfig">Nouveau pays : </label>
                        <div class="col-md-7">
                        	<input type="text" name="newcountry"  id="newcountry" value="" placeholder="Entrer un nouveau pays" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <button type="submit" name="validation" class="col-md-12 formconfig">Valider</button>
                    

				</fieldset>
			</form>
		</div>

		<div class="col-md-6 col-sd-12">
			<form method="post" action="">
				<fieldset>

					<legend>Changement de mot de passe :</legend>

					<div class="form-group">
                        <label for="ancienpassword" class="col-md-5 control-label formconfig">Ancien mot de passe : </label>
                        <div class="col-md-7">
                        	<input type="password" name="ancienpassword"  id="ancienpassword" value="" placeholder="Entrer votre ancien mot de passe" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="nouveaupassword" class="col-md-5 control-label formconfig">Nouveau mot de passe : </label>
                        <div class="col-md-7">
                        	<input type="password" name="nouveaupassword"  id="nouveaupassword" value="" placeholder="Entrer votre nouveau mot de passe" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="confirmpassword" class="col-md-5 control-label formconfig">Confirmation de mot de passe : </label>
                        <div class="col-md-7">
                        	<input type="password" name="confirmpassword"  id="confirmpassword" value="" placeholder="Confirmer votre nouveau mot de passe" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>
                    
                    <button type="submit" name="validation" class="col-md-12 formconfig">Valider</button>

				</fieldset>


			</form>
		</div>
	</div>
</div>