<section class="col-md-12">

		<div class="coordonnees jumbotron">
			<address>
				<p>CIN3WA</p>
				<p>TOUR SEBASTOPOL</p>
				<p>3 Quai Kléber</p>
				<p>67000 STRASBOURG</p>
			</address>
			<br>
			<p>Téléphone portable : 00.00.00.00.00</p>
			<p>Courriel : test@test.com</p>
			<br>
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2639.253711536229!2d7.7417598!3d48.5858408!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796c8494ac86f49%3A0x2e07316b11ffae72!2s3+Quai+Kl%C3%A9ber%2C+67000+Strasbourg!5e0!3m2!1sfr!2sfr!4v1432735039402" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>

            <form class="jumbotron" method="" action="">
                <fieldset>
                    <legend>Envoyez directement un email</legend>
                        <div class="row">
                            <div class="col-md-3"><label for="nom">Votre nom : </label></div>
                            <input class="col-md-6" type="text" id="nom" name="nom" placeholder="Entrez votre nom ici"/><br/>
                        </div>
                        <div class="row">
                            <div class="col-md-3"><label for="email">Votre email : </label></div>
                            <input class="col-md-6"type="email" id="email" name="email" placeholder="Entrez votre adresse email ici" required/><br/>
                        </div>
                        <div class="row">
                            <div class="col-md-3"><label for="contenutexte">Votre contenu : </label></div>
                            <textarea class="col-md-6" name="contenutexte" id="contenutexte" placeholder="Entrez votre texte ici" cols="30" rows="10" required></textarea><br/>
                        </div>
                        <div class="row">
                        	<div class="col-md-3"></div>
                        	<input class="col-md-6"type="submit" value="Envoyer">
                        </div>
                </fieldset>
           	</form>
		
	</section>