<div>
	<ul>
		<li><a href="#"><img src="style/img/CV1.jpg" alt="Patrick" width="200px" height="200px">Patrick</a></li>
		<li><a href="#"><img src="style/img/CV2.gif" alt="Fredéric" width="200px" height="200px">Fredéric</a></li>
		<li><a href="#"><img src="style/img/CV3.png" alt="Nicolas_G" width="200px" height="200px">Nicolas G</a></li>
		<li><a href="#"><img src="style/img/CV4.jpg" alt="Nicolas_M" width="200px" height="200px">Nicolas M</a></li>
		<li><a href="#"><img src="style/img/CV5.gif" alt="Alexandre" width="200px" height="200px">Alexandre</a></li>
	</ul>
</div>
