<div>
	<ul>
		<li><a href="#"><img src="../style/img/#.jpg" alt="nomCV" width="200px" height="200px">Lorem</a></li>
		<li><a href="#"><img src="../style/img/#.jpg" alt="nomCV" width="200px" height="200px">Ipsum</a></li>
		<li><a href="#"><img src="../style/img/#.jpg" alt="nomCV" width="200px" height="200px">Dolor</a></li>
		<li><a href="#"><img src="../style/img/#.jpg" alt="nomCV" width="200px" height="200px">Sit</a></li>
		<li><a href="#"><img src="../style/img/#.jpg" alt="nomCV" width="200px" height="200px">Amet</a></li>
	</ul>
</div>