</section>
<footer class="footer">
<div class="factice"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<h4 class="text-uppercase">Partager</h4>
				<ul class="social-list">
                	<li><a href="#" class="social social-fb"></a></li>
                	<li><a href="#" class="social social-tw"></a></li>
                	<li><a href="#" class="social social-db"></a></li>
                	<li><a href="#" class="social social-rss"></a></li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4 class="text-uppercase">Recherche film</h4>
				<form method="post">
					<input type="search" id="search" name="search" maxlength="50" placeholder="Film, acteur,..." class="recherche">
					
				</form>
			</div>
			<div class="col-md-4">
				<h4 class="text-uppercase">Les cinés du coin</h4>
				<ul>
					<li><a href="index.php?page=Ugc">UGC Ciné Cité</a></li>
					<li><a href="index.php?page=Odyssee">L'Odyssée</a></li>
					<li><a href="index.php?page=Vox">Pathé VOX</a></li>
					<li><a href="index.php?page=Star">Le Star</a></li>
				</ul>
			</div>
		</div>
	</div>
	<style>
		.recherche
		{
			color:black;
		}
	</style>
</footer>