</section>
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<h4>Informations</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, incidunt.</p>	
			</div>
			<div class="col-md-4">
				<h4>Mentions légales</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, necessitatibus.</p>
			</div>
			<div class="col-md-4">
				<h4>Liens utiles</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, sequi.</p>
			</div>
		</div>
	</div>
</footer>