</section>
<footer class="container-fluid">
	<div>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. A dolore est sunt ad eligendi, qui, eum voluptas, cupiditate tempore asperiores optio assumenda officiis voluptatum. Qui sit obcaecati, eligendi corporis aperiam.
	</div>
	<div>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. A dolore est sunt ad eligendi, qui, eum voluptas, cupiditate tempore asperiores optio assumenda officiis voluptatum. Qui sit obcaecati, eligendi corporis aperiam.=
	</div>
	<div>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. A dolore est sunt ad eligendi, qui, eum voluptas, cupiditate tempore asperiores optio assumenda officiis voluptatum. Qui sit obcaecati, eligendi corporis aperiam.
	</div>
</footer>