<div class="row">
	<div class="col-md-12">
		<article>
			<header class="page-header">
			</header>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><?= 'Created by '.$author_id.' - '.$create ?></h3>
				</div>
				<div class="panel-body">
					<textarea class="panel-textarea" name="panel-textarea" rows="5" readonly><?= $content ?></textarea>
				</div>
			</div>
		</article>
	</div>
</div>