<header class="container-fluid">
	<nav>
		<ul>
			<li><a href="index.php?page=home">HOME</a></li>
			<li><a href="index.php?page=livredor">LIVRE D'OR</a></li>
			<li><a href="index.php?page=contact">CONTACT</a></li>
			<li><a href="index.php?page=cv">CV</a></li>
		</ul>
	</nav>
	<div>
		<ul class="bxslider">
		  <li><img src="style/img/slider1.jpg" /></li>
		  <li><img src="style/img/slider2.jpg" /></li>
		  <li><img src="style/img/slider3.jpg" /></li>
		</ul>
	</div>
</header>
<section class="container body">
