<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CIN3WA</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav text-uppercase">
    		<li><a href="index.php?page=home">Home</a></li>
    		<li><a href="index.php?page=livredor">Livre d'or</a></li>
    		<li><a href="index.php?page=contact">Contact</a></li>
    		<li><a href="index.php?page=cv">CV</a></li>
        <li><a href="index.php?page=register">register</a></li>

        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <form class="navbar-form navbar-right">
		<a href="index.php?page=register"><button type="button" class="btn btn-primary">Register</button></a>
    <a href="index.php?page=login"><button type="button" class="btn btn-primary">Login</button></a>
      </form>
    </div><!-- /.navbar-collapse -->
	</div>
</nav>
<nav class="container">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
					<li><a href="index.php?page=home">Home</a></li>
					<li class="active">You are here</li>
				</ol>
			</div>
		</div>
	</div>
</nav>	
<section class="container body section">
