<header class="container-fluid">
	<nav>
		<ul>
			<li><a href="index.php?page=home">HOME</a></li>
			<li><a href="index.php?page=livredor">LIVRE D'OR</a></li>
			<li><a href="index.php?page=contact">CONTACT</a></li>
			<li><a href="index.php?page=cv">CV</a></li>
		</ul>
	</nav>
	<div>
		<img src="http://www.mes-coloriages-preferes.biz/Images/Small/Animaux-Singe-108753.png">
	</div>
</header>
<section class="container body">
