<div class="row">
	<div class="col-md-12">
		<header class="jumbotron">
		  <h1>Hello fellow visitor !</h1>
		  <img class="logo" src="./style/img/logo.png" alt="logo" />
		  <p>This website is an attempt to create a simple CMS featuring common components (members system, news/article/guestbook systems, and a real-time chat... because snapchat sucks).</p>
		  <p>Take a look at our website, navigate around and enjoy our good stuff.<br />Something wrong ? Fell free to join our <a href="">Github A-Team</a> to participate and improve this project.</p>
		  <p><a class="btn btn-primary btn-lg" href="https://github.com/mr-am" role="button">Contact us</a></p>
		</header>
	</div>

</div>

<div class="row">
	<div class="col-md-12">
		<ul class="bxslider text-justify carousel">
			<?php
			require('./apps/carroussel.php');
			?>
		</ul>
	</div>
</div>
