<div class="row">
	<div class="col-md-12">
		<header class="jumbotron">
		  <h1>Hello fellow visitor !</h1>
		  <img class="logo" src="./style/img/logo.png" alt="logo" />
		  <p>This website is an attempt to create a simple CMS featuring common components (members system, news/article/guestbook systems, and a real-time chat... because snapchat sucks).</p>
		  <p>Take a look at our website, navigate around and enjoy our good stuff.<br />Something wrong ? Fell free to join our <a href="">Github A-Team</a> to participate and improve this project.</p>
		  <p><a class="btn btn-primary btn-lg" href="https://github.com/mr-am" role="button">Contact us</a></p>
		</header>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<ul class="bxslider text-center carousel">
		  <li><span>Article 1: Comment tailler un crayon sans en foutre partout ?</span><img src="style/img/pen.jpg" class="img-responsive" alt="Responsive image" /></li>
		  <li><span>Article 2: Comment péchô une fille avec une belle voiture ?</span><img src="style/img/car1.jpg" /></li>
		  <li><span>Article 3: Comment péchô quand on a plus de voiture ?</span><img src="style/img/car2.jpg" /></li>
		</ul>
	</div>
</div>
