<div class="row">
	<div class="col-md-12">
		<header class="jumbotron">
		  <h1>Hello fellow visitor !</h1>
		  <img class="logo" src="./style/img/logo.png" alt="logo" />
		  <p>This website is an attempt to create a simple CMS featuring common components (members system, news/article/guestbook systems, and a real-time chat... because snapchat sucks).</p>
		  <p>Take a look at our website, navigate around and enjoy our good stuff.<br />Something wrong ? Fell free to join our <a href="">Github A-Team</a> to participate and improve this project.</p>
		  <p><a class="btn btn-primary btn-lg" href="https://github.com/mr-am" role="button">Contact us</a></p>
		</header>
	</div>

</div>



<div class="row">
	<div class="col-md-12">
		<ul class="bxslider text-justify carousel">
			<li>
				<div class="news jumbotron">
			  	<h1><?=$tableau_res[0]['title']?></h1>
			  	<h2>Date de création :<?=$tableau_res[0]['time_create']?></h2>
				<p><?=$tableau_res[0]['content']?></p>
				<h2>Date de modification : <?=$tableau_res[0]['time_update']?></h2>
				</div>
			</li>
			<li>
				<div class="news jumbotron">
				<h1><?=$tableau_res[1]['title']?></h1>
				<h2>Date de création :<?=$tableau_res[1]['time_create']?></h2>
				<p><?=$tableau_res[1]['content']?></p>
				<h2>Date de modification : <?=$tableau_res[1]['time_update']?></h2>
				</div>
			</li>
			<li>
				<div class="news jumbotron">
				<h1><?=$tableau_res[2]['title']?></h1>
			  	<h2>Date de création :<?=$tableau_res[2]['time_create']?></h2>
				<p><?=$tableau_res[2]['content']?></p>
				<h2>Date de modification : <?=$tableau_res[2]['time_update']?></h2>
				</div>
			</li>
		</ul>
	</div>
</div>
