<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">
	    <title>Projet commun</title>
	    <meta name="viewport" content="width=device-width, maximum-scale=1.0">
		<script src="js/jquery-2.1.4.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.bxslider.min.js"></script>
        <link rel="stylesheet" href="style/bootstrap.min.css" />
        <link rel="stylesheet" href="style/jquery.bxslider.css" />
        <link rel="stylesheet" href="style/style.css" />
        <link rel="stylesheet" type="text/css" href="style/styletchat.css">
		<script src="chat.js"></script>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/tchat.php'); ?>
		<?php require('apps/'.$page.'.php'); ?>
		<?php require('apps/footer.php'); ?>
	</body>
	<script>
/* A mettre dans un fichier séparé, c'est plus propre :) */
        $(function(){
            $('.bxslider').bxSlider({
                mode : "fade",
                auto : true
            });
        })
    </script>
</html>