<h1>Vous trouvez notre site génial? dites-le nous</h1>

<form action="index.php?page=livredor" method="post">

<h2 class="Title">Identification</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="champLogin" class="col-sm-2 control-label">Login : </label>
                <div class="col-sm-10">
                    <input type="text" name="login"  value="<?php echo strip_tags($login) ?>" id="champLogin" placeholder=" *" maxlength="32" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="captcha" class="col-sm-2 control-label">Recopiez le mot : "<?php echo captcha(); ?>"</label>
                <div class="col-sm-10">
                    <input type="text" name="captcha" id="captcha" value="<?php echo strip_tags($captcha) ?>" maxlength="32" class="form-control"/><br />
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h2 class="Title">Votre commentaire</h2>
            <div class="form-group">
                <label for="champCom" class="col-sm-3 control-label">Commentaire : </label>
                    <div class="col-sm-9">
                         <textarea name="commentaire" class="champCom" maxlength="512" placeholder="pas plus de 512 caractères" class="form-control" max-width="100%"><?php echo strip_tags($commentaire) ?></textarea>
                    </div>
            </div>
            <button type="submit" name="validationLivredor" >Envoyer</button>
        </div>
    </div>
</form>



