<h1>Veuillez vous identifier pour profiter de toutes les fonctionnalités du site</h1> 

            <form action="index.php?page=login" method="post">


                <h2 class="Title">Identification</h2>

                <div class="row">

                <div class="col-md-12">
                    <form action="../apps/login.php" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label for="champLogin" class="col-sm-2 control-label">Login : </label>
                            <div class="col-sm-10">
                                <input type="text" name="login"  value="<?php echo strip_tags($login) ?>" id="champLogin" placeholder="*" maxlength="32" class="form-control">
                            </div>
                        </div>   

                        <!-- Password -->
                        <div class="form-group">
                            <label for="champPassword" class="col-sm-2 control-label">Password : </label>
                            <div class="col-sm-10">
                                <input type="password" name="password"  id="champPassword" value="<?php echo strip_tags($password) ?>" placeholder="*" maxlength="32" class="form-control">
                            </div>
                        </div>
                        <input type="hidden" name="redirect" value="<?= isset($_GET['redirect']) ? $_GET['redirect'] : ""; ?>">
                        <button type="submit" name="validation">Envoyer</button>
                    </form> 
                </div>    
<!-- 
                <div class="col-md-12">
                    <form action="index.php?page=register" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">Pas encorre inscrit? c'est ici : </label>
                            <div class="col-sm-10">
                                <button type="submit" name="inscription" >Inscription</button>
                            </div>
                         </div>

                    </form>    

                </div> -->