
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Equipe de développeurs : <strong>the winner team</strong> </h1>
        <h2>Alex - Pat - Fred - Nico - Nico</h2>
        <h3>3WA STRASBOURG</h3>
    </div>
</div> 

<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Informatique et libertés</h1>
        <p>
            Les informations recueillies font l’objet d’un traitement informatique destiné
            à l'équipe <strong>the winner team</strong> uniquement dans un but d'une gestion de notre aimable clientèle.
            Les destinatiares de ces données sont <strong>the winner team</strong>.
            Conformément à la loi « Informatique et Libertés », vous bénéficiez d’un droit d’accès et de rectification aux informations qui vous
            concernent. Si vous souhaitez exercer ce droit et obtenir communication des
            informations vous concernant, veuillez vous adresser à <strong>the winner team</strong>
            vous pouvez également, pour des motifs légitimes, vous opposer au traitement des données vous concernant.
        <p>
    </div>
</div> 

<div class="panel panel-default">
    <div class="panel-heading">
        <h1>droits d'auteur</h1>
        <p>
            L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents téléchargeables et les représentations iconographiques et photographiques.
            La reproduction de tout ou partie de ce site sur un support électronique quel qu'il soit est formellement interdite, sauf autorisation expresse de l'équipe <strong>the winner team</strong>. 
        <p>
    </div>
</div> 

<style>

    h1, h2, h3{
        text-align: center;
    }

    .panel{
        width : 750px;
        margin: 0 auto;
        margin: 50px 0;
        border: 2px solid rgb(50,150,150);
    }

</style>


